### ISSUE TITLE
Windows and Linux support

### ISSUE THREAD

**Issue by erperejildo** [twilio/twilio-cli#111] opened 2019-09-03 14:22 UTC
#### Issue Summary

I get different issues on both systems.

#### Steps to Reproduce

**Linux**:
After running `twilio login` I get this error:

> Error: Cannot autolaunch D-Bus without X11 $DISPLAY

**Windows**:
After running `twilio autocomplete` I get this error:

> Autocomplete is not currently supported in Windows

#### Technical details:

* twilio-cli Version: 1.4.2
* Node.js Version: 10.15.3 (Linux) and 10.16.2 (Windows)

**Comment by childish-sambino** [comment] 2019-09-20 13:54
The Linux issue is a duplicate of https://github.com/twilio/twilio-cli/issues/1. Env vars can be used for auth if keytar is not available.

The Windows issue is known and in the upstream plugin (https://github.com/oclif/plugin-autocomplete/issues/2 and https://github.com/oclif/plugin-autocomplete/issues/6). Once the plugin supports auto-complete on Windows, so will `twilio-cli`.

**Closed by childish-sambino** 2019-09-20 13:54 UTC
