### ISSUE TITLE
Remove strict requirement for -l debug and -o flags from twilio-cli

### ISSUE THREAD

**Issue by deathemperor** [twilio/twilio-cli#202] opened 2020-07-21 08:30 UTC
### Issue Summary
Getting an unknown error when initializing a serverless project using verify template. Then unable to add -l debug to twilio-cli

### Steps to Reproduce
1. Install twilio-cli
2. run `twilio serverless:init verify-sample --template=verify`
3. run `twilio serverless:init verify-sample --template=verify -l debug`

### Technical details:
* twilio-cli version: 2.5.0
* node version: 12.10.0
* Command output with debug logging enabled (adding `-l debug` to the end of the command): *unable to run with -l debug*

![Screen Shot 2020-07-21 at 3 29 50 PM](https://user-images.githubusercontent.com/4255482/88031634-0984f580-cb67-11ea-87dd-98385aac44f3.png)

**Comment by philnash** [comment] 2020-07-22 01:28
Hey there! The `serverless` command is provided by the [@twilio-labs/plugin-serverless](https://github.com/twilio-labs/plugin-serverless) plugin and ultimately calls [@twilio-labs/create-twilio-function](https://github.com/twilio-labs/create-twilio-function/) which I maintain and has not implemented the `-l` flag yet ([issue has been raised for this here](https://github.com/twilio-labs/create-twilio-function/issues/57))

I am concerned about the error though. There shouldn't be an issue between the plugin and the CLI.

Can you run `twilio plugins` and tell me which version of @twilio-labs/plugin-serverless you are using?

Are you able to run the same command with `create-twilio-function`?

```bash
npm init twilio-function verify-sameple --template=verify
```

Thanks for reporting this.

**Comment by deathemperor** [comment] 2020-07-22 05:10
> Can you run `twilio plugins` and tell me which version of @twilio-labs/plugin-serverless you are using?

Runnning `twillio plugins` I only get this (no version):

```
twilio plugins
@twilio-labs/plugin-serverless
```

but I've just reinstalled the plugin so is it safe to assume it's the latest?

> Are you able to run the same command with `create-twilio-function`?

I'm able to create the verify-sample project with this command.

Thanks for your support @philnash .

**Comment by philnash** [comment] 2020-07-22 05:33
Thanks for following up @deathemperor. I have some more questions as I am trying to reproduce this error.

Running `twilio plugins:update` should give you the latest version of the serverless plugin, which should be 1.7.1.

Do you have a profile set up for the Twilio CLI? (Did you call `twilio login` or `twilio profiles:create` at some point?)

Do the other `twilio serverless` commands work for you? You should be able to run them within the project you have now been able to create.

**Comment by deathemperor** [comment] 2020-07-22 10:10
> Do you have a profile set up for the Twilio CLI? (Did you call `twilio login` or `twilio profiles:create` at some point?)

yes I do.



> Do the other `twilio serverless` commands work for you? You should be able to run them within the project you have now been able to create.

yes it does, like `twilio serverless:start`. In fact, I've always been able to run `twilio serverless:start` and `twilio serverless:deploy` and always failed to run the init. But back then I create the twilio project myself and then add the verify js files. Yesterday I tried doing the verify template again (there was some issue with the serverless deployment) to find a fix and found this. FYI my node version is 12.

**Comment by eshanholtz** [comment] 2020-07-24 23:40
It looks like not all plugins are supporting the `-l` and `-o` flags. The issue to fix the messaging has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by eshanholtz** [comment] 2020-07-31 16:59
@deathemperor Forgot to mention, for further help with the `serverless` plugin, please [open a separate issue in the `plugin-serverless` github repo](https://github.com/twilio-labs/plugin-serverless/issues/new)

**Comment by bnb** [comment] 2024-10-15 14:17
since this is for a plugin that's currently publicly archived and there's been no additional feedback from the original issue author, I'm going to go ahead and close it. Please fee free to either let us know here if this is still an issue that's relevant to the core twilio CLI, or feel free to create another issue referencing this one.

**Closed by bnb** 2024-10-15 14:17 UTC
Labels: type: twilio enhancement, status: help wanted, triage queue
