### ISSUE TITLE
Issue generating authentication passcode for Video Chat 

### ISSUE THREAD

**Issue by PGrauss** [twilio/twilio-cli#209] opened 2020-08-02 19:28 UTC
### Issue Summary
I am having trouble creating an authentication passcode as I am trying to implement Twilio Video Chat into my iOS Application. Issue is seen with command: twilio rtc:apps:video:deploy --authentication passcode

### Steps to Reproduce
1. Install Twilio CLI. - Success
2. Run twilio login and follow prompts to login to your Twilio account. - Success
3. Run twilio plugins:install @twilio-labs/plugin-rtc. - Success
4. Run twilio rtc:apps:video:deploy --authentication passcode. - Error

### Code Snippet
```node
twilio rtc:apps:video:deploy --authentication passcode
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-cli version: 4.6.0 (? - not sure, see below)
* node version: 12.18.3
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
Phillips-MacBook-Pro:~ PGrauss$ twilio rtc:apps:video:deploy --authentication passcode -l debug
[DEBUG] Config File: /Users/PhilthyPhil/.twilio-cli/config.json
[DEBUG] Using profile: Favor
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.48.1, node.js v12.18.3, darwin 19.5.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sun, 02 Aug 2020 19:25:37 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQfc7f22f267ac49dd86a795ec37f0ffc5","twilio-request-duration":"0.038","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS62bfe281afee316e0308fc4935bafc2a/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.48.1, node.js v12.18.3, darwin 19.5.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sun, 02 Aug 2020 19:25:37 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ2419feb9a4664eab99f9d27ca3359402","twilio-request-duration":"0.017","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/PhilthyPhil/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:77:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/Users/PhilthyPhil/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/Users/PhilthyPhil/.twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/2.6.0/libexec/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/Cellar/twilio/2.6.0/libexec/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/Cellar/twilio/2.6.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
 ›   Error: EEXIT: 1
 ›   Code: EEXIT
```

**Comment by childish-sambino** [comment] 2020-08-03 15:16
Duplicate of https://github.com/twilio-labs/plugin-rtc/issues/16

**Closed by childish-sambino** 2020-08-03 15:16 UTC
