### ISSUE TITLE
Twilio Zork "I don't know the word Zork"

### ISSUE THREAD

**Issue by styerfoam** [twilio/twilio-cli#238] opened 2021-01-18 02:07 UTC
### Issue Summary
I am trying to complete the Zork challenge and the install of Twilio (2.16.0) succeeded with no issue. When I run twilio zork I receive the error "I don't know the word Zork"

### Steps to Reproduce
1. Install Twilio 2.16.0
2. run twilio Zork
3. receive above error

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-cli version: 2.16.0
* node version:14.15.4
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
[DEBUG] TwilioCliError: TypeError: Cannot read property 'rl' of undefined
    at Zork.run (/usr/local/Cellar/twilio/2.16.0/libexec/src/commands/zork.js:13:13)
    at async Zork._run (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
```

**Comment by thinkingserious** [comment] 2021-01-19 21:56
Hello @styerfoam,

Thank you for reporting this! I was able reproduce this locally, both using an npm install and brew install.

Here was the error I received in the version installed with brew:

Without `-l debug`:
```bash
/Users/ethomas/.twilio-cli/runtime_modules/twilio-cli/node_modules/glkote-term/src/glkote-dumb.js:266
		this.rl = options.rl
		                  ^

TypeError: Cannot read property 'rl' of undefined
    at new DumbDialog (/Users/ethomas/.twilio-cli/runtime_modules/twilio-cli/node_modules/glkote-term/src/glkote-dumb.js:266:21)
    at runZork (/Users/ethomas/.twilio-cli/runtime_modules/twilio-cli/node_modules/zorkjs/zork.js:44:13)
    at /Users/ethomas/.twilio-cli/runtime_modules/twilio-cli/node_modules/zorkjs/zork.js:62:9
    at WriteStream.<anonymous> (/Users/ethomas/.twilio-cli/runtime_modules/twilio-cli/node_modules/zorkjs/zork.js:33:7)
    at WriteStream.emit (node:events:379:20)
    at emitCloseNT (node:internal/streams/destroy:169:10)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

With `-l debug`:
```bash
[DEBUG] Config File: /Users/ethomas/.twilio-cli/config.json
[DEBUG] Found command "zork" plugin: twilio-cli
[DEBUG] Error loading zork: {}
 » I don't know the word "zork".
[DEBUG] TwilioCliError: I don't know the word "zork".
    at Zork.run (/usr/local/Cellar/twilio/2.16.0/libexec/src/commands/zork.js:13:13)
    at async Zork._run (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/local/Cellar/twilio/2.16.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
```

In the version installed with npm:

Without `-l debug`:
```bash
» I don't know the word "zork".
 ›   Error: EEXIT: 1
 ›   Code: EEXIT
```

With `-l debug`:
```bash
[DEBUG] Config File: /Users/shwetharadhakrishna/.twilio-cli/config.json
[DEBUG] Found command "zork" plugin: twilio-cli
[DEBUG] Error loading zork: {}
 » I don't know the word "zork".
[DEBUG] TwilioCliError: I don't know the word "zork".
    at Zork.run (/Users/shwetharadhakrishna/DI/codehq/cli/twilio-cli/src/commands/zork.js:13:13)
    at async Zork._run (/Users/shwetharadhakrishna/DI/codehq/cli/twilio-cli-core/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/Users/shwetharadhakrishna/DI/codehq/cli/twilio-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/Users/shwetharadhakrishna/DI/codehq/cli/twilio-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/Users/shwetharadhakrishna/DI/codehq/cli/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
 ›   Error: EEXIT: 1
 ›   Code: EEXIT
```

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by tonyh-fff** [comment] 2021-02-02 05:19
I'm having the same issue. Playing Twilioquest and trying to solve the zork challenge

**Comment by delente333** [comment] 2021-04-08 03:47
Check here, 😘 : http://web.mit.edu/marleigh/www/portfolio/Files/zork/beginner-transcript.html

**Comment by shelbyz-prft** [comment] 2021-04-13 20:13
Looks like it is addressed by a PR to the zorkjs repo (https://github.com/dprothero/zorkjs/pull/3) and not something that twilio-cli would need to make changes for.

**Comment by dprothero** [comment] 2021-05-24 19:05
@thinkingserious I just published version 1.0.4 of `zorkjs`, so that should fix this issue.

**Comment by onuzbee** [comment] 2021-05-25 10:31
`Twilio zork` works for me, since I had manually removed runtime node_module for testing locally previously. 

Need to check if it'll still download the latest version of zorkjs on runtime if a 1.0.3 module is already present for existing installation. Else, we should be able to bump the zorkjs version in package.json to the latest and close this issue.

**Comment by Sindhura3** [comment] 2021-05-25 16:18
A new version of Zork has been published with the fix. Since it's a runtime dependency for Twilio CLI, please delete the runtime module cli folder (.twilio-cli/runtime_modules/twilio-cli) and rerun the 'twilio zork' command.

**Closed by Sindhura3** 2021-05-25 16:18 UTC
Labels: status: help wanted, type: bug
